### ISSUE TITLE
Chart doesn't stay in container when printing

### ISSUE THREAD

**Issue by mRamzii** [carbon-design-system/carbon-charts#1015]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [x ] Other

### Issue description
Hello,
First of all I would like to thank all the contributors to the project, it's by far the best library I've came across.

My chart is well presented when looking at the HTML but when choosing to print, it seems like the svg doesn't keep its shape ( doesn't stay in the container )

![image](https://user-images.githubusercontent.com/54007844/117298711-f930d380-ae77-11eb-9999-2eb086ba9d85.png)

But when I try to print it :

1. Using Chrome
![image](https://user-images.githubusercontent.com/54007844/117298824-18c7fc00-ae78-11eb-8933-0598649014a7.png)

2.  Firefox
![image](https://user-images.githubusercontent.com/54007844/117298902-2ed5bc80-ae78-11eb-9fb9-95ecf6696f84.png)

Notice that there is a huge difference between Chrome and Firefox printing, maybe this gives a hint ??

#### Steps to produce the issue
I guess just put a chart inside a container and set its width to "100%", it will overflow when printing.

I have also tried setting a special css rule @print to reduce the width of the graph when printing but that didn't work aswell.

I was able though, to set 
`@media print { 
svg.bx--cc--chart-svg {
	overflow: hidden;
}}`

This didn't help aswell
#### Current behavior
Chart doesn't  keep size

#### Expected behavior
Keep its size ?

**Comment by theiliad** [comment]
Hi,
Thank you for your kind words :)

This is definitely the first time that I'm hearing about this issue, so I'd need to do some more research

Looking at c3js I'm seeing the same kind of issues

![image](https://user-images.githubusercontent.com/14989804/117333342-d5b15d00-ae66-11eb-97df-3a0512a09dd9.png)

Now, trying to print our demoes on storybook I get a pretty good result

![image](https://user-images.githubusercontent.com/14989804/117333630-1f01ac80-ae67-11eb-832e-5f4e578898de.png)

Which makes me think that maybe the way that you're setting up the chart could potentially cause these issues.

As far as I know most of these kind of rendering issues with SVGs are because of the improper explicit definitions of the dimensions of the holder of the main SVG...

So your chart holder could potentially not have super clear `px` value definitions for its width & height...

Are you using percentages?

Could you compare to our storybook demos and see whether there are any changes you can make?

Also keep in mind that the amount of space the chart needs could be the problem. e.g. if you try to print this page you'll have the same issues https://carbon-design-system.github.io/carbon-charts/?path=/story/simple-charts-line--line-discrete

However if you try to print this it'll look fine https://carbon-design-system.github.io/carbon-charts/iframe.html?id=simple-charts-line--line-discrete&viewMode=story

That's because the printing size results in a crop of the page width... This is why some sites include a `print this page` button. I think I'm seeing the same issue in your demo, your chart could potentially be too wide relative to the page, and the printing logic crops it out

Please lmk if any of this helps

**Comment by theiliad** [comment]
Hi,
Thank you for your kind words :)

This is definitely the first time that I'm hearing about this issue, so I'd need to do some more research

Now, trying to print our demoes on storybook I get a pretty good result

![image](https://user-images.githubusercontent.com/14989804/117334315-da2a4580-ae67-11eb-916c-4e9151598141.png)

Which makes me think that maybe the way that you're setting up the chart could potentially cause these issues.

As far as I know most of these kind of rendering issues with SVGs are because of the improper explicit definitions of the dimensions of the holder of the main SVG...

So your chart holder could potentially not have super clear px value definitions for its width & height...

Are you using percentages?

Could you compare to our storybook demos and see whether there are any changes you can make?

Also keep in mind that the amount of space the chart needs could be the problem. e.g. if you try to print this page you'll have the same issues https://carbon-design-system.github.io/carbon-charts/?path=/story/simple-charts-line--line-discrete

However if you try to print this it'll look fine https://carbon-design-system.github.io/carbon-charts/iframe.html?id=simple-charts-line--line-discrete&viewMode=story

That's because the printing size results in a crop of the page width... This is why some sites include a print this page button. I think I'm seeing the same issue in your demo, your chart could potentially be too wide relative to the page, and the printing logic crops it out

Please lmk if any of this helps

**Comment by mRamzii** [comment]
Thank you for your response,

I think I might be onto something, the example Sandbox that you shared works well, the proprtions are kept, but I noticed that when I go into that same sandbox (https://codesandbox.io/s/bqv1z) and launch only the existing code (without the carbon component from carbon-design's docs), I get the same issue. (Here: https://bqv1z.csb.app/)

![image](https://user-images.githubusercontent.com/54007844/117336584-a9b0ce80-ae9c-11eb-9e2b-9b0cf4b10500.png)

When printing :

![image](https://user-images.githubusercontent.com/54007844/117336623-b6352700-ae9c-11eb-8165-5ace6a9ea350.png)

There must be someting in the parent in the storybook causing it to render correctly on printing, im talking about here : https://carbon-design-system.github.io/carbon-charts/iframe.html?id=simple-charts-line--line-discrete&viewMode=story

In the code the "app" div has defined dimensions (percentages), I have also tried specifying the width using pixels/cms without any success.

I have managed though, to get the chart at the correct size when printing, but i had to set the width to 40% so it's no takes the full width on the normal page (but does when printing)

I hope I was clear enough, thank you for you assistance

**Comment by theiliad** [comment]
I think it's actually just the width of the chart, try dropping a div with an absolute width that is equal to the chart, and try printing that, I think some of that will be cropped too

**Comment by mRamzii** [comment]
Hello,

After days and days of trying, I still haven't managed to have a full-screen width chart for both the web and printing...

I believe that the issue as you mentionned before, is related to the SVG, since the width and height are explicitly specified :

Correct me if I'm wrong, but I believe that the values for the "width" and "height" in the <svg width= height= /> come from the initialization of the Charts object with these same dimensions.

This is why, even when applying a class for printing to change the size when in print mode, this doesn't work, the SVG doesn't change size, I'm talking about something like this :
`@media print {
              carbon-line-chart: {
                         width: 500px !important;
              }
}`

This kind of makes sense since @media print property can't change the width= height= properties of the SVG.

I still haven't found a work-around, something to dynamically change the width and height parameters on the <svg> tag when In print mode.

Thank you and have a good day.

**Comment by theiliad** [comment]
I think we have everything we need for now, lmk if you'd like me to re-open the issue with any additional comments
