### ISSUE TITLE
Uncaught Error: unknown type: cancel

### ISSUE THREAD

**Issue by swapnilpatil242** [carbon-design-system/carbon-charts#1062]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [x] Other

#### charts version:
```
"@carbon/charts": "0.41.50",
"@carbon/charts-react": "0.41.50",
"d3": "5.14.2"
```
### Issue description and Steps to produce the issue
I have updated **package.json** file with below dependencies
```
"@carbon/charts": "0.41.50",
"@carbon/charts-react": "0.41.50",
"d3": "5.14.2"
```
and other packages in my **package.json** file
```
"react": "17.0.2",
"react-dom": "17.0.2",
"@carbon/ibm-security": "1.41.0"
```
After that I did below steps
1. removed node_module folder
2. removed package-lock.json
3. npm install
4. npm start and got error like **Uncaught Error: unknown type: cancel**

If I do above same steps, adding below **step 3**, **above issue got resolved**

1. removed node_module folder
2. removed package-lock.json
3. **npm install -S @carbon/charts@0.41.50 @carbon/charts-react@0.41.50 d3@5.14.2**
4. npm install
5. npm start and its run successfully

Not sure why this happening, Is anyone have any idea about this? Any leads would be helpful

### Screenshot or recording
<img width="486" alt="Screenshot 2021-07-08 at 9 43 45 PM" src="https://user-images.githubusercontent.com/7311903/124956404-94d7ef00-e035-11eb-97c1-71b83dbb357b.png">

**Comment by theiliad** [comment]
Hi, I'd need more details in order to look into this.

Could you pls create a sandbox and reproduce the issue so that I can see the exact conditions that cause it?

You can use the Edit on Codesandbox button in one of our demos
https://carbon-design-system.github.io/carbon-charts/?path=/story/simple-charts-bar-simple--vertical-simple-bar-discrete

Feel free to re-open with additional details
