### ISSUE TITLE
Carbon charts resources

### ISSUE THREAD

**Issue by mathieudaudelin** [carbon-design-system/carbon-charts#1552]
Hi there,
UX designer here wondering if you guys plan on providing resources for Figma editor.
Thank you for your concern.

Best regards,
Mathieu Daudelin

**Comment by theiliad** [comment]
I'm going to close for now. Once the kit is made public, you should see links either on the carbondesignsystem.com website or medium

**Comment by Szermer** [comment]
Any news on a release date?

**Comment by justin-m-schmidt** [comment]
Hi, I would also like to find out when this will be released. Any update=

**Comment by theiliad** [comment]
# Due to the numerous requests we received, **we've decided to publish the Alpha kit as public 🎉** 

**Here's the link:
https://www.figma.com/community/file/1342888187036080999/alpha-carbon-charts-library**

Keep in mind, this is still an Alpha release, there are many unfinished pieces, and areas we'd want to refactor/recreate. We will announce a future beta release when it's available
