### ISSUE TITLE
[Bug]: "Export as PNG" and "Export as JPG" feature is exporting a blank image.

### ISSUE THREAD

**Issue by Jayateerth13** [carbon-design-system/carbon-charts#1566]
### Name

Jayateerth Kamatgi

### Are you an IBM employee?

- [X] Yes

### What happened?

**Issue:**
The Export to PNG and Export to JPG options for a carbon chart is exporting a blank image in Firefox browser. The same options exports only a part of the image in Chrome browser. Behavior is different across different browser for different charts. The issue can be reproduced in Carbon Charts Storybook.

**Example:**
Exported Donut Chart image in Chrome browser from Carbon Charts React Storybook.
![myChart (1)](https://github.com/carbon-design-system/carbon-charts/assets/40992344/fe5f7572-0fc6-48e1-9602-855b993754ad)

**Expected:**
Upon exporting, the entire image needs to visible across all browsers consistently.

### Version

@carbon/charts-react (v1.7.6)

### What priority level would this be in your opinion?

P1

**Comment by nstuyvesant** [comment]
Tried to download JPG and PNG from https://charts.carbondesignsystem.com/react/?path=/story/simple-charts-donut--donut with Firefox 114.0.2 on macOS and got blanks. Did not appear to be chart-specific. Safari is also having some problems - partial image.

**Comment by Vineet-Dubey** [comment]
This issue is not resolved, I am getting following error on safari 17

`Refused to load data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB4IAAAHgCAYAAABAc6CbAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAHgqADAAQAAAABAAAB4AAAAAAv8jo8AABAAElEQVR4AezdCbglaV0f/reX6dm6p2ffmEXAgE4gAirJgCPKKAkRCIg6RlYB0Zg/EWOAqGDTShbXZ9yIwUGWCRI0oICokOiAMExYAi6ILKLOTDP71stMd09v//7W8Pace+45556lzr3nnvt5n+fes1TVW1WfeuutOvWr9611R46mIhEgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIDA3Aisn5s1sSIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAg0AgIBCsIBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQm...ACCCCAAAIIIIAAAggggAACCCCAAAIIFL0AgeCi/wkAgAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAAChSZAILjQzijHgwACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACRS9AILjofwIAIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIBAoQkQCC60M8rxIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIBA0QsQCC76nwAACCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCBQaAIEggvtjHI8CCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCBQ9AIEgov+JwAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggUmgCB4EI7oxwPAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggUvcD/B0Vf9BGeOByNAAAAAElFTkSuQmCC because it does not appear in the frame-src directive of the Content Security Policy.`

**Comment by nstuyvesant** [comment]
@Vineet-Dubey - your content security policy headers are not permitting data URLs. Normally, this is set via HTTP headers on your server...
```
Content-Security-Policy: frame-src 'self' data:;
```

It can also be set via the meta tag in HTML...
```html
<meta http-equiv="Content-Security-Policy" content="frame-src 'self' data:">
```

Here's some background...
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

**Comment by Vineet-Dubey** [comment]
@nstuyvesant - I've got the RCA, it is only for line chart but work well for combo chart in safari.
Line chart should be fixed

**Comment by nstuyvesant** [comment]
Hi @Vineet-Dubey. Not sure we have the steps to reproduce your issue and it does not appear to be the same as the initial issue.

Could you please open a new issue and provide information about which of the packages and what version you are using, development environment (React, Angular, etc.), bundler and produce a minimal StackBlitz repro of your issue?

I just opened this StackBlitz example of the LineChart component and the downloads work fine on Safari 17.5:
https://stackblitz.com/edit/zsmdap?file=index.js

**Comment by Vineet-Dubey** [comment]
@nstuyvesant new issue raised here https://github.com/carbon-design-system/carbon-charts/issues/1830
