### ISSUE TITLE
Svelte - adapter-static - Error

### ISSUE THREAD

**Issue by aaaknot30** [carbon-design-system/carbon-charts#1655]
This issue pops up when we do a 'npm run build' command.
We are using @sveltejs/adapter-static for build.  Any help appreciated.

file:///home/bash/projects/cyborg/.svelte-kit/output/server/entries/pages/megamap/_page.svelte.js:11
/* empty css                      */import { GroupedBarChart, SimpleBarChart, StackedBarChart, LineChart } from "@carbon/charts";
                                             ^^^^^^^^^^^^^^^
SyntaxError: Named export 'GroupedBarChart' not found. The requested module '@carbon/charts' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@carbon/charts';
const { GroupedBarChart, SimpleBarChart, StackedBarChart, LineChart } = pkg;

**Comment by nstuyvesant** [comment]
@aaaknot30 - in place of `GroupedBarChart`, please use `BarChartGrouped`. A long time ago, one of the authors of the `@carbon/charts-svelte` package renamed a few of the components to follow more logical naming.

Here is the mapping from `@carbon/charts` to `@carbon/charts-svelte` component names...
| @carbon/charts | @carbon/charts-svelte |
| - | - |
| SimpleBarChart | BarChartSimple |
| GroupedBarChart | BarChartGrouped |
| StackedBarChart | BarChartStacked|

Also, some advice... instead of...
```
import pkg from '@carbon/charts';
const { GroupedBarChart, SimpleBarChart, StackedBarChart, LineChart } = pkg;
```
do this...
```
import { BarChartGrouped, SimpleBarChart, StackedBarChart, LineChart } from '@carbon/charts';
```
While they create the same runtime result, some bundlers are more efficient at tree-shaking with the latter.

**Comment by theiliad** [comment]
Hi @aaaknot30, I will close the issue now, but pls do let us know if @nstuyvesant's response did not fix the issue, and we can re-open :)
