### ISSUE TITLE
[Research]: Survey software teams about Carbon Charts usage

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-charts#1682]
### Name

Jean Servaas

### Are you an IBM employee?

- [X] Yes

### Summary

Our last survey of this kind was done in the beginning of 2021 and we used it to help prioritize your dataviz requirements for the rest of that year and beyond(i.e. new chart types, maps, gauges, a11y improvements etc.)

This is a link to the original survey to give you an idea of the kinds of questions that we were asking at the time and the tooling we used for the survey.

https://www.surveygizmo.com/s3/6605624/Carbon-Data-Visualization-Survey

@sstrubberg has done a few more surveys since and I've been working to sync with him to pick his brain on what he's learned about what kinds of questions to ask and what tooling we've been using more recently to survey folks.

We still need to flesh out this issue a bit more to help @alina-jacob-ibm figure out
—what survey tool to use
—who the audience for this survey will be/how to get to them
—how to draft questions that yield the most helpful responses without creating too much of a lift for respondants

### Justification

Until we get our IBM Telemetry service fully automated, we don't have a window (although we do have an idea) into what teams are using most from the charts library and what their biggest gaps are. Another manual survey will help us prioritize new enhancements and updates that will be the most impactful for software. This last survey ended up highlighting a need for svg maps, which we delivered in the following year.

In general, and this was the premise we used when buidling the Charts Figma kit, the most commonly used chart components are the most basic ones. 
—line
—bar
—pie
—scatter

Another thing that could come up is the need for more keyboard accessibility within charts.

### Desired UX and success metrics

A survey still will give us a more accurate pulse of our audience and more credibility with our leadership and will go along way towards drafting a squad OBR (Outcome Based Roadmap). That is the goal of this workstream.

### "Must have" functionality

Ask @sstrubberg about the sample size audience we're targetting here; the goal is also to help @alina-jacob-ibm familiarize herself with the data viz docs and the charts library so she can become more familiar with the audience and their needs.

### Specific timeline issues / requests

This will be Alina's first issue (check on current sprint number with @theiliad) and will be expected to roll over into the next sprint as she acclimates herself to the Data Viz docs and library.

### Available extra resources

Alina can lean on me, Eliad and Scott Strubberg for support while working on this issue.

### What priority level would this issue be in your opinion?

P1

**Comment by alina-jacob-ibm** [comment]
[heart]         Alina Jacob reacted to your message:
________________________________
From: jeanservaas ***@***.***>
Sent: Tuesday, November 7, 2023 9:32:01 PM
To: carbon-design-system/carbon-charts ***@***.***>
Cc: Alina Jacob ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [carbon-design-system/carbon-charts] [Research]: Survey software teams about Carbon Charts usage (Issue #1682)

Name Jean Servaas Are you an IBM employee? Yes Summary Our last survey of this kind was done in the beginning of 2021 and we used it to help prioritize your dataviz requirements for the rest of that year and beyond(i. e. new chart types, maps,
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2I-rqJY1AVJZEK8Ts6uuTXXWJrvkFWhNb3ClZsZUa_lDh2stnVLZLrzdlcB1W3hL9VY0uEnHSmycFLP8QosY3w_N4lo9KKPtLGiJQdVFQzdxc0Y$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Name

Jean Servaas

Are you an IBM employee?

  *    Yes

Summary

Our last survey of this kind was done in the beginning of 2021 and we used it to help prioritize your dataviz requirements for the rest of that year and beyond(i.e. new chart types, maps, gauges, a11y improvements etc.)

This is a link to the original survey to give you an idea of the kinds of questions that we were asking at the time and the tooling we used for the survey.

https://www.surveygizmo.com/s3/6605624/Carbon-Data-Visualization-Survey<https://www.surveygizmo.com/s3/6605624/Carbon-Data-Visualization-Survey>

@sstrubberg<https://github.com/sstrubberg> has done a few more surveys since and I've been working to sync with him to pick his brain on what he's learned about what kinds of questions to ask and what tooling we've been using more recently to survey folks.

We still need to flesh out this issue a bit more to help @alina-jacob-ibm<https://github.com/alina-jacob-ibm> figure out
—what survey tool to use
—who the audience for this survey will be/how to get to them
—how to draft questions that yield the most helpful responses without creating too much of a lift for respondants

Justification

Until we get our IBM Telemetry service fully automated, we don't have a window (although we do have an idea) into what teams are using most from the charts library and what their biggest gaps are. Another manual survey will help us prioritize new enhancements and updates that will be the most impactful for software. This last survey ended up highlighting a need for svg maps, which we delivered in the following year.

In general, and this was the premise we used when buidling the Charts Figma kit, the most commonly used chart components are the most basic ones.
—line
—bar
—pie
—scatter

Another thing that could come up is the need for more keyboard accessibility within charts.

Desired UX and success metrics

A survey still will give us a more accurate pulse of our audience and more credibility with our leadership and will go along way towards drafting a squad OBR (Outcome Based Roadmap). That is the goal of this workstream.

"Must have" functionality

Ask @sstrubberg<https://github.com/sstrubberg> about the sample size audience we're targetting here; the goal is also to help @alina-jacob-ibm<https://github.com/alina-jacob-ibm> familiarize herself with the data viz docs and the charts library so she can become more familiar with the audience and their needs.

Specific timeline issues / requests

This will be Alina's first issue (check on current sprint number with @theiliad<https://github.com/theiliad>) and will be expected to roll over into the next sprint as she acclimates herself to the Data Viz docs and library.

Available extra resources

Alina can lean on me, Eliad and Scott Strubberg for support while working on this issue.

What priority level would this issue be in your opinion?

P1

**Comment by jeanservaas** [comment]
@sstrubberg I took @alina-jacob-ibm off of this issue as we discussed yesterday in favor of a few system squad issues that Lauren has queued up for her. After our conversation... I'd like to look at folding in a few chart library usage questions into your survey for end of year. So maybe we can get together and think about what those might be when the time is right. Of course, first, we'd just like to see who's using the chart library. Beyond that, since charts is basically in maintenance mode, we know we're not creating specs for new charts at the moment. However, it would be nice to target some enhancements like keyboard accessibility within charts etc, based on users responses.
