### ISSUE TITLE
Add ability to display duplicate labels

### ISSUE THREAD

**Issue by bkrissIBM** [carbon-design-system/carbon-charts#181]
#### I am submitting a...

- [ ] Feature request

#### charts version:
LineChart v0.86 from @carbon/charts-react

### Issue description
Duplicate labels get ignored and end up showing multiple data points per label.

#### Steps to produce the issue
I have an array of objects with unique dateTimes for every 30 minutes of the day, which can span across several days. The data looks something like this:
![screen shot 2019-02-07 at 11 26 51 am](https://user-images.githubusercontent.com/33705160/52430493-cf877700-2acb-11e9-9682-cb14c17d00b6.png)

I shorten/reformat each dateTime before adding to the labels array so that the labels are more readable. The labels array ends up looking something like this: `labels: [‘12 AM’, ‘6 AM’, ‘12 PM’, ‘6 PM’, ‘12 AM’]`

If I have multiple days coming back, then I will have multiple instances of each time of day, which leads to my graph looking something like this:
![screen shot 2019-02-07 at 11 20 58 am](https://user-images.githubusercontent.com/33705160/52430843-9b608600-2acc-11e9-9e00-9f1834a3e007.png)

#### Expected behavior
I'd like to be able to have multiple duplicate labels that all have unique data. For example, the following graph allows for multiple instances of 6 AM, 6PM, etc.:
![screen shot 2019-02-07 at 11 48 06 am](https://user-images.githubusercontent.com/33705160/52431837-a2889380-2ace-11e9-9b1c-da66bc00ff74.png)

**Comment by theiliad** [comment]
@bkrissIBM Thank you for creating an issue. Multiple points/questions:
1. We're working on continuous time scales that'll let you use javascript date objects or strings for dates, rather than having to process them into an array of labels manually. So look out for that in the future 🙂
2. Seems like you are trying to show multiple points on the y-axis for a single x-axis value, is that right? (It'll help if you can share some code for your data and how you process it into the labels)
3. If the answer to number 2 is a yes, then you should consider using multiple datasets. Multiple y-values for a single x-value is not something that makes sense in 1 dataset within a line chart, usually you'd use a 2nd dataset for your 2nd point, and so on...
4. I didn't quite understand your point about:
> If I have multiple days coming back, then I will have multiple instances of each time of day, which leads to my graph looking something like this

Please explain that more in detail, and I think something that'll really help me for that one is to see your data, and how you process it.

Thanks

**Comment by bkrissIBM** [comment]
1. Awesome! 
2. No, that's what's currently happening, but it isn't what I want. LineChart works great when I want to show just one day's worth of data, but anything over and it breaks. I'll give a more detailed example:

If the user wants to see 2 days worth of data, and wants data points for every 6 hours of both days, then my labels array will look like ['12 AM',  '6 AM',  '12 PM',  '6 PM', '12 AM',  '6 AM',  '12 PM',  '6 PM', '12 AM'].

I would want the graph to show all 9 of those individually with one data point for each label so it looks like a traditional line graph. What actually happens when I pass in that array, is it automatically condenses those labels down to  '12 AM',  '6 AM',  '12 PM',  '6 PM' and shows 2 data points for each label, which isn't what I want.

It sounds like the continuous time scales you mentioned will probably solve this issue for me. Is there a chance that feature will be available by end of February?

**Comment by theiliad** [comment]
I see, definitely a bug that we should fix ASAP.

I don't think the time scales will be ready to use by end of Feb, but I'll make sure this issue is fixed.

**Comment by theiliad** [comment]
Update @bkrissIBM I've fixed this issue in PR #183, however this causes an issue with the fill & stroke colors of chart elements, and also the legend.

So once I fix those, we can merge in, and you'll be able to use it, but I've already included in the PR deploy preview an example of a line chart with your labels.

**Comment by bkrissIBM** [comment]
@theiliad Awesome, thanks!

**Comment by theiliad** [comment]
This isn't directly addresses by #275, however the underlying issue here was the time-series relationship of those labels, which is addressed in the PR
