### ISSUE TITLE
Chart legend covers up the chart.

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon-charts#191]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect

#### charts version:
0.8.6

### Issue description
When the `+` icon in the legend is clicked, the legend covers up the chart itself. The legend should come up in such a way so that the chart is still visible.

#### Steps to produce the issue
Code sand box link to view the issue - https://codesandbox.io/s/p9pk464p80

### Screenshot or recording
<img width="268" alt="screenshot 2019-02-13 at 12 53 35 pm" src="https://user-images.githubusercontent.com/46365045/52694008-6782d600-2f8e-11e9-9c8d-2ffa76471ae0.png">

**Comment by theiliad** [comment]
@dianatran18 need your input here

**Comment by dianatran18** [comment]
Yup that's correct. See example below of how the expanded legend should appear. 
<img width="826" alt="screen shot 2019-03-01 at 9 52 20 am" src="https://user-images.githubusercontent.com/43549567/53645945-09015d00-3c08-11e9-862c-6bf261e43c9a.png">

The legend should not cover the chart, so users can refer to the legend to identify the values on the chart.

**Comment by theiliad** [comment]
@dianatran18 How would that work if there is so screen space to the right?

**Comment by pjena98** [comment]
We are still waiting for a fix and request ETA

**Comment by dianatran18** [comment]
@shixiedesign any thoughts?

**Comment by shixiedesign** [comment]
This is a tough one, though I think if there's no screen space then legend covering up chart is unavailable. We can improve the experience by making the "covering" behavior more intentional, eg. modal to cover up all of chart, and expose "hide/show" function of the legends, and proper button to close the legend pop up...

Quick exploration: 

![image](https://user-images.githubusercontent.com/15144993/59872586-b76c1200-935f-11e9-86e8-8ea53fe47189.png)

**Comment by shixiedesign** [comment]
**Options**

![image](https://user-images.githubusercontent.com/15144993/60029036-fe128280-9665-11e9-93ec-90d416aae34d.png)

**Comment by shixiedesign** [comment]
Please refer to https://github.com/carbon-design-system/carbon-charts/issues/287 for the latest overflowing legend designs.
