### ISSUE TITLE
BarChart throws `NS_ERROR_FAILURE` as component rendering it unmounts.

### ISSUE THREAD

**Issue by ian-henderson** [carbon-design-system/carbon-charts#240]
#### I am submitting a...

Bug

#### charts version:

0.10.2

### Issue description

When a component that renders the react package's BarChart component unmounts, an `NS_ERROR_FAILURE` error is thrown in the browser's console.

Here are the last two functions that I think were called:

- [`BaseAxisChart.setYScale()`](https://github.com/carbon-design-system/carbon-charts/blob/v0.10.2/packages/core/src/base-axis-chart.ts#L329)

- [`BarChart.resizeChart()`](https://github.com/carbon-design-system/carbon-charts/blob/v0.10.2/packages/core/src/bar-chart.ts#L269)

#### Steps to produce the issue

1. Mount a component that renders BarChart.
2. Unmount that component.

#### Current behavior

BarChart throws an `NS_ERROR_FAILURE` error as it unmounts.

#### Expected behavior

BarChart doesn't throw an error.

### Screenshot or recording
<img width="901" alt="Screen Shot 2019-04-09 at 3 41 18 PM" src="https://user-images.githubusercontent.com/10488956/55834109-c07a7080-5ade-11e9-9ad8-8998bbc38b6a.png">

**Comment by cal-smith** [comment]
Doing some brief debugging, part of the issue _seems_ to be related to the resize observer calling `resizeChart` _after the element is removed from the DOM_. We can test this by manually deleting the chart container in the inspector (and we can walk through the stack trace with `Pause on exceptions` enabled in the debugger)

 Specifically calling `getBBox` on a non-existent element seems to trigger the `NS_ERROR_FAILURE`.

The simple solution is to check that we still have an element we can render into before we make any other DOM calls (i.e. run a new `document.querySelector` ... since I don't believe we can guarantee any cached elements will still be valid).

**Comment by cal-smith** [comment]
Yep, implementing the simple fix for `PieChart` stopped the errors ... I'd like to entertain a few more ideas before committing to this approach (since it will require updates in all the chart classes)

**Comment by theiliad** [comment]
Good catch @cal-smith. Something I can think of right off the bat is implementing a function for all wrappers to call upon unmounting components. We will remove at that point any listeners or observers binding to the charts

**Comment by cal-smith** [comment]
From slack, seems like a similar issue: https://peretz.slack.com/archives/CCA7L4MS9/p1555060480002100

![image](https://user-images.githubusercontent.com/1744185/56037632-c8642b80-5cfd-11e9-9163-c52b7863069b.png)

https://codesandbox.io/s/5zw2zl4104

The codesandbox gives me the NS_ERROR ... I'll have to test in chrome, to see if it handles this differently

**Comment by theiliad** [comment]
This seems to have been fixed by the rewrite. Feel free to re-open if the issue still persists
