### ISSUE TITLE
[Restyle] Tooltips

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#285]
## Tooltips styling & spec 
Currently identified 3 types of tooltips that occurs in charts:
- [ ] Axis truncated label hover tooltip
- [ ] General hover tooltip on charts (single value), used on pie, donut, bar, scatter, etc
- [ ] Line chart hover tooltip (multiple values)

![(4) Tooltips](https://user-images.githubusercontent.com/15144993/59991511-4c476780-960d-11e9-99d5-5b2a15aa32d8.png)

**Comment by theiliad** [comment]
@shixiedesign Could we also get some min/max width values for the tooltip box
![image](https://user-images.githubusercontent.com/14989804/60221884-5786d700-9849-11e9-8a12-723224ba61bd.png)

**Comment by shixiedesign** [comment]
My to-dos: 
- [ ] loading/skeleton state design & animation
- [ ] tooltip min/max size spec

**Comment by CynZhang** [comment]
@shixiedesign for the line chart hover tooltip, I believe what you are proposing is to automatically show all values along the same grid line. In practice, there could be more than 2 lines, and the data points may overlap or be too close to each other, how would you render the tooltips in such case? What about one tooltip that could show all values?

**Comment by shixiedesign** [comment]
See spec image above: 
When data points are too close, tooltips just stack, with 2px spacing. Larger value on top. If values are equal, the first category in legend places on top. 
![image](https://user-images.githubusercontent.com/15144993/60445734-6b359300-9be5-11e9-838b-5c6e365fcf08.png)

**Comment by CynZhang** [comment]
@shixiedesign that's great, thank you.
Our team is building line charts to show time series data, and one problem with the current tooltip is it doesn't show timestamp or the value of x-axis, it only shows the y value. In your examples, the assumption is every label is shown and corresponds to a grid line. In practice, when we render a very line chart with large amount of data, we only show every other label on the x-axis due to limited width, and therefore it's crucial for the tooltip to show the hidden x label.

**Comment by natashadecoste** [comment]
@shixiedesign I just pushed some rough code for the gridline tooltips (https://github.com/carbon-design-system/carbon-charts/pull/307). 

I need some specs for:
- tooltip width (is it fixed, min-width, etc): currently using cascaded styles from original tooltip
- line hover (dashed/bolded, etc)
- tooltip padding: specifically how far to the right is the tooltip from the datapoint? visually looks around 4px to me 
- any adjustments to the threshold? currently the threshold is 10 on either side of the line. Having no threshold means the tooltip will flicker on and off (since gridlines are 1px)

**Comment by shixiedesign** [comment]
Hi! @natashadecoste I finally got specs for you: 

> tooltip width (is it fixed, min-width, etc): currently using cascaded styles from original tooltip

Tooltips should get auto widths usually, aka wider if content is long. `Min-width: 20px` and `max-width: 128px`

![image](https://user-images.githubusercontent.com/15144993/62171406-7834c780-b2f4-11e9-8ea2-5fde583777dc.png)

> line hover (dashed/bolded, etc)

grid line hover color: `$focus` which should give it Blue60 on light themes and White on dark themes.
line style: `1px, gap 2, dash 2`

> how far to the right is the tooltip from the datapoint?

`4px` is correct! Tooltip should be either to the right or left of the hovered-grid-line depending on whether there's space in the chart area.

![image](https://user-images.githubusercontent.com/15144993/62171458-9bf80d80-b2f4-11e9-8b16-bca59e9217ba.png)


> any adjustments to the threshold?

We spoke about this on Slack. Waiting to try out 25%.

**Comment by natashadecoste** [comment]
@shixiedesign just FYI the tooltips are positioned to be within the chart container which currently includes other elements outside the chart (right positioned legend for example). **after the refactor**, tooltip should get constrained to the chart container which would only contain the chart and it should look like your screenshot above.

**Comment by shixiedesign** [comment]
## Design updated after revision

![(1) Chart tooltips](https://user-images.githubusercontent.com/15144993/63240405-142b6200-c215-11e9-97c1-a3e38d5c46da.png)

**Comment by shixiedesign** [comment]
@natashadecoste Here is the tooltip for bar charts. Hover darkens the hovered bar by 30%

![image](https://user-images.githubusercontent.com/15144993/63469458-df472700-c42f-11e9-8976-8bee218be469.png)

Tooltip layout: 

![image](https://user-images.githubusercontent.com/15144993/63469823-c3905080-c430-11e9-8ac7-af0c93eba51b.png)

**Comment by natashadecoste** [comment]
design decision on tooltips for smaller charts 
![image](https://user-images.githubusercontent.com/14351335/65164245-86f14e00-da0a-11e9-9824-79ea76b9788a.png)

tooltips need to **truncate or multiline**

**Comment by theiliad** [comment]
These specs have all been implemented in Q3 2019. Let me know if anything is missing
