### ISSUE TITLE
Allow removal of legends/labels in charts and removal of '%' labels at the outer of donut charts

### ISSUE THREAD

**Issue by jagdishkumar1** [carbon-design-system/carbon-charts#379]
#### I am submitting a...

- [ ] Feature request

### Issue description

I am trying to achieve something like below:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/2225196/67260687-40d05400-f4ba-11e9-8188-e1aab3e92953.png">

what I am able to achieve with current carbon-charts is below:
![image](https://user-images.githubusercontent.com/2225196/67260610-d8817280-f4b9-11e9-90f7-353d4b257db6.png)

so , what can I do to closely match with the expected behaviour shown in first snapshot ?

1) How can I use to reduce the gap between the donut chart and labels on the right ?
2) How can I use to remove the labels (%) displayed at the outer of donut chart ?
3) What config can I use to remove labels displayed on the right ?
4) How can I remove the grid in bar chart ?
5) Labels/legends should always appear to the right of donut chart, and not like whats shown in second snapshot with `+` sign at the top right of donut chart

**Comment by theiliad** [comment]
This is mostly up for @cameroncalder's review. Would we want to allow for any of those customizations?

**Comment by scottdickerson** [comment]
@theiliad with the new legend options in 0.16.24 version, can we just add a "disabled" legend option to achieve?

**Comment by theiliad** [comment]
> @theiliad with the new legend options in 0.16.24 version, can we just add a "disabled" legend option to achieve?

yeah we could, it's just a matter of design approval for disabling legends

**Comment by jagdishkumar1** [comment]
Similar requirement on line chart as well .. 

Expectation:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/2225196/67929134-a02d1300-fbe2-11e9-926c-1c56ed103745.png">

**Comment by jagdishkumar1** [comment]
Is there any config which can support the positioning on legends in any chart ?

Expectation : 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/2225196/67943817-edb87880-fc00-11e9-98f5-7aff7b1ef617.png">

Here, legends are positioned at bottom of bar chart

**Comment by cameroncalder** [comment]
@theiliad @jagdishkumar1  Many of the points above are quite acceptable and should allow for configuration. Particularly the following:

Removing the legend has appropriate use cases. For example, if there is only a single data category being visualized and the title of the chart provides enough context.

The option to remove labels on a donut/pie chart is reasonable as well. Or making the labels numbers to the whole instead of percentages. If labels are removed though, I recommend leveraging the Carbon charts legend style instead of the style shown in the example.

**Comment by pcoccoli** [comment]
I also need to remove the legend (since there's only a single data category in my charts).  This is required for my 1Q release.  @cameroncalder does your comment above count as design approval?

**Comment by theiliad** [comment]
> Is there any config which can support the positioning on legends (top / right / left / bottom) in any chart ?
> 
> Expectation :
> <img alt="image" width="244" src="https://user-images.githubusercontent.com/2225196/67943817-edb87880-fc00-11e9-98f5-7aff7b1ef617.png">
> 
> Here, legends are expected to be positioned at the bottom of bar chart

You can position the legend using this config:

```js
{
  legend: {
    position: "top" | "left" | "bottom" | "right"
  }
}
```

**Comment by jagdishkumar1** [comment]
@cameroncalder @theiliad let me know if the features requested as part of this issue are in place, so that we can start leveraging them ? Thanks

**Comment by zhenwan** [comment]
I also need to  remove the labels (%) displayed at the outer of donut chart, is this feature already available in latest version ?

**Comment by natashadecoste** [comment]
PR #927 should provide the option to enable/disable the labels on pie/donut

**Comment by jeanservaas** [comment]
@daniel-m-s 

Sorry, took me a second to realize what was going on here. Cameron is OG Charts and has approval rights. He's giving approval on:

- Removing the legend in appropriate use cases. (For example, if there is only a single data category being visualized and the title of the chart provides enough context).

- The option to remove labels on a donut/pie chart is reasonable as well. Or making the labels numbers to the whole instead of percentages.

But to your question above daniel, i think what he's saying is to use Carbon styling if the whole numbers are removed from the donut chart and used instead IN the legend next to the label.

Here's an example from our guidance of how we do that: the percentage comes after the label in semibold. @cameroncalder is this what you meant?

![image](https://user-images.githubusercontent.com/43144260/149974737-ea4d8a56-0efd-40ae-b79e-ff185ee6638e.png)

**Comment by daniel-m-s** [comment]
Thanks @jeanservaas ! Your screenshot shows what we need, just with the option to display absolute values instead of percentages.
@theiliad, if you have an outlook when you'll be able to implement this, let me know please.
