### ISSUE TITLE
[LineChart]: in the new scaleType: time, I can't get multiline tooltips to show up for my data, it appears from the demo data that they only show up if the x exactly matches one of the gridlines

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-charts#397]
#### I am submitting a...

- [x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
0.16.25

### Issue description
You can see this limitation in the demo data page, by hovering over a non-gridlined datapoint
![image](https://user-images.githubusercontent.com/6663002/67802613-7dbbbe00-fa59-11e9-966f-33190da0d6c8.png)

Versus a gridlined datapoint:
![image](https://user-images.githubusercontent.com/6663002/67802668-9deb7d00-fa59-11e9-825c-8965d2878a33.png)

**Comment by theiliad** [comment]
I don't think the gridline tooltips are working at all.

On a continuous axis you need a continuous tooltip, because you will still have a real domain within the gridlines that need to be addressed.

(Refer to the Intermediate Value Theorem - https://www.mathsisfun.com/algebra/intermediate-value-theorem.html)

I suggest the tooltip persisting onHover at any point within the grid.

If the developer knows that there is a lack of relation between the points on the graph, they could switch to the gridline tooltips through some configs.

**Comment by ryshah** [comment]
@theiliad I second the need for the fix. All my time series data points are aligned but not with gridlines and tooltip only shows one data point. 

<img width="879" alt="Screen Shot 2020-01-29 at 2 22 08 PM" src="https://user-images.githubusercontent.com/13667662/73394417-34bb1600-42a3-11ea-93ac-ac00541822de.png">

Is it possible to have gridlines configured along the datapoints? It would be nice to include timestamp as part of tooltip for time series charts

**Comment by gvnmagni** [comment]
This issue will be be automatically solved by https://github.com/carbon-design-system/carbon-charts/issues/478

**Comment by gvnmagni** [comment]
Russel, this image shows the application of the updated tooltip to this specific case

<img width="1184" alt="Screenshot 2020-03-18 at 16 34 07" src="https://user-images.githubusercontent.com/18484576/76978216-b855c280-6936-11ea-83ef-8cb44a80efbc.png">
