### ISSUE TITLE
Chart animation-in direction

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/carbon-charts#431]
- [x] Scatter & bubble: animate the nodes starting from the x-axis and transitioning upward, instead of top-down.
- [ ] Line: animate the node in at the same placement as their related line instead of top-down to meet the line.
- [ ] Bar: animate the bars starting from the x-axis and transitioning upward, instead of top-down.

**Comment by theiliad** [comment]
> * [ ]  Scatter & bubble: animate the nodes starting from the x-axis and transitioning upward, instead of top-down.

Fei is working on that.

> * [ ]  Line: animate the node in at the same placement as their related line instead of top-down to meet the line.
> * [ ]  Bar: animate the bars starting from the x-axis and transitioning upward, instead of top-down.

How necessary would you say these 2 tasks are? In order to get bars to render both vertically and horizontally we switched them from svg rectangles to paths, which means we'd need additional code in there to animate the height.

And in the case of line, line uses the scatter graph nodes which would animate in in their own way. Just trying to keep the code clean here and avoid adding a lot of extra logic. Is there a compromise we can make in terms of animating a lines in a different way?
