### ISSUE TITLE
Tool tip needs line grey divider lines

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-charts#457]
I believe the tool tips get a light grey line to help separate data points. @shixie or @cameroncalder  can provide the spec but assume it’s grey 20. And let me know if I’m wrong here but it seems it needs additional help to separate. 

<img width="434" alt="Screen Shot 2019-12-30 at 12 36 50 PM" src="https://user-images.githubusercontent.com/32881239/71595409-14136b00-2b01-11ea-86b3-0c7b16d4d9d7.png">

**Comment by natashadecoste** [comment]
@shixiedesign @cameroncalder if you can provide a token for all themes that would be great (or multiple if it doesnt properly align)

**Comment by cameroncalder** [comment]
@natashadecoste 

![light UI](https://user-images.githubusercontent.com/50155706/71949748-5c362b80-319a-11ea-9e24-5052d3d69e6d.png)

![dark UI](https://user-images.githubusercontent.com/50155706/71949758-648e6680-319a-11ea-8b42-726402c72ca6.png)
These color values will be for both g90 & g100 since both themes have gray-100 chart backgrounds

**Comment by mjabbink** [comment]
👍
