### ISSUE TITLE
Color concerns with Heat map

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon-charts#466]
Hi, Regarding this data vis:
<img alt="image" width="792" src="https://user-images.githubusercontent.com/12818623/72361107-ed3b6400-36be-11ea-9261-f4bec56c53b7.png">

Please reconsider color choices by reviewing this video:
https://youtu.be/R-oiKt7bUU8?t=2621

**Comment by anne-stevens** [comment]
The video addresses a number of flaws with the rainbow heat scale used.  I believe the issue with the heat map above is that a bidirectional heat scale was used for unidirectional data.  A bidirectional heat scale suits data that ranges from, say, -1000 to +1000.  In that case, dark blue would be mapped to -1000 and red to +1000 and the colour inflection point would land neatly at zero in the data.  The trick is how to handle the colour inflection when the data is asymmetrical (eg. -10 to +1000.  In that case, putting the inflection point at the midpoint of the data range - 495 - could be misleading.). 

A one directional heat scale would be preferable in this instance.  Either that or change the data used to something that goes from a negative to a positive value.  That might make for a more satisfying illustration.

**Comment by mjabbink** [comment]
@theiliad I think we can get Accurat team to revise and create better specs for development.

**Comment by theiliad** [comment]
@mjabbink We definitely do need to spec out the component.

From a design perspective I don't think that we've got much beyond that photo that Shixie created.

**Comment by mjabbink** [comment]
Assign to Accurat

**Comment by gvnmagni** [comment]
Hi, Accurat here!

Our overall rule would be to use a sequential scale when we have values that are all positive or all negative. In case of both, such as when we are dealing with temperatures that go above and below zero, it's better to use a divergent scale.

Divergent scales require 3 values and 3 correspondent colors.

- Min value = Color A (let's say blue, just to be consistent with the attached image)
- Inflection point = White
- Max Value = Color B (red, in this case)

While Min e Max could be automatically detected from data, the inflection point could differ depending on the data nature. Our opinion is to set it as 0 (zero) as a default choice in order to comply with the most common cases and to include a sort of flag within the code that specify otherwise, this way we'll have a default behaviour that could be modified in case of need.

![Heatmap - color scale](https://user-images.githubusercontent.com/18484576/74664086-4fdfbe00-519d-11ea-8205-50a0b69b8836.png)

**Comment by gvnmagni** [comment]
I'm posting this image again for Russel, this way he can have a clear idea of the solution for this issue.

![74664086-4fdfbe00-519d-11ea-8205-50a0b69b8836](https://user-images.githubusercontent.com/18484576/76977297-6c564e00-6935-11ea-91d2-320521ef5407.png)
