### ISSUE TITLE
Bar chart width

### ISSUE THREAD

**Issue by sophiiae** [carbon-design-system/carbon-charts#470]
For all types of bar chart (Simple bar chart, Grouped bar chart, Stacked bar chart), the width of bars binds with maxWidth instead of width.
<img width="431" alt="751e7100-022b-11ea-9e2d-0cf0ac54973e" src="https://user-images.githubusercontent.com/18622886/72842310-18492900-3c66-11ea-8511-52e32e72e5ea.png">

**Comment by natashadecoste** [comment]
closing this issue - latest carbon charts uses **both** `width` and `maxWidth` suitably. 

-> if config `width` is provided, it is returned with the `getBarWidth` function, otherwise _the best width is returned_ in respect to the user either passing in a `maxWidth` or defaulting to the carbon-charts maxWidth `16`

in the posted photo, you might actually be _setting the width property to 0_  rather than not including it at all as an option, and in that case the chart will use the `maxWidth` instead. 

storybook latest cc version:
![image](https://user-images.githubusercontent.com/14351335/109864982-831eaf00-7c31-11eb-9e69-348a020f4650.png)
