### ISSUE TITLE
Rotation of tick labels on the X axis

### ISSUE THREAD

**Issue by ilariaventurini** [carbon-design-system/carbon-charts#519]
Hi, I'm Ilaria from Accurat 👋

#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

v0.29.7

### Issue description

As is:

![as is](https://user-images.githubusercontent.com/44204353/75696636-32861600-5cac-11ea-86f4-d2938abea9c4.png)

How I think it should be:

![](https://user-images.githubusercontent.com/44204353/75696634-3154e900-5cac-11ea-9a74-16f1d4574585.png)

because in this case it is not necessary to rotate the labels.

In the chart options (inside `ticks`) there is the numerical value `rotateIfSmallerThan` which represents the estimated length of a label.
Then inside `components/axes/axis`, the length of the tick labels is estimated in this way:

    const estimatedTickSize = width / scale.ticks().length / 2;

so if `estimatedTickSize < rotateIfSmallerThan`, then ticks are rotated.

I think that we should use `axis.tickValues().length` instead of `scale.ticks().lenght` because that is the real number of the ticks that we set it before.
The other represents the default number of ticks generated by D3.

**Comment by theiliad** [comment]
Good catch @ilariaventurini! Do we have a PR for that? Should I make one?

**Comment by ilariaventurini** [comment]
@theiliad If you confirm that it is an actual problem, we will work on it!
We have seen that replacing variables may not be enough and we would like to do some additional tests.

**Comment by theiliad** [comment]
@theiliad I have a local PR somewhere where I've changed ` / 2` to ` / 1.4` or something to that effect and I'm getting a better behaviour. Would you please try that and let me know?

Otherwise I believe the other approach we can take is actually calculating the physical space each tick will take up

**Comment by caesarsol** [comment]
@theiliad I think ilaria's proposal is conceptually more correct, the actual number of ticks which is rendered is `axis.tickValues().length`; the `scale.ticks().lenght` is a different number, not reflecting reality.

The option of calculating the width of every tick is pretty neat, but we have to consider it's a pretty heavy DOM operation because requires to render the same chart twice.

I think @ilariaventurini future fix will suffice!

**Comment by theiliad** [comment]
> @theiliad I think ilaria's proposal is conceptually more correct, the actual number of ticks which is rendered is `axis.tickValues().length`; the `scale.ticks().lenght` is a different number, not reflecting reality.
> 
> The option of calculating the width of every tick is pretty neat, but we have to consider it's a pretty heavy DOM operation because requires to render the same chart twice.
> 
> I think @ilariaventurini future fix will suffice!

Yeah, I agree with Ilaria's idea. Let's do that
