### ISSUE TITLE
Single Tooltip Enhancement

### ISSUE THREAD

**Issue by caesarsol** [carbon-design-system/carbon-charts#550]
Issue opened by Accurat to keep track of the discussions around the "Single Tooltip" design and development.

This is the last design iteration, still to be worked and discussed on:
![image](https://user-images.githubusercontent.com/1799710/78118959-00311b00-7408-11ea-8eac-2d179ce866c1.png)

**Comment by stegue88** [comment]
Below a couple of versions: 
1 - the tooltip mirrors the tabular format of the data. We can see that there are many redundancies and the overall look is quite messy. Moreover, when there are more than 4/5 datapoints the tooltip start to be very crowded.

After discussion with the team, we moved to a “minimal” version that seems to work better, but exceptions to the format are to be considered (i.e bubble charts)

2 - We collapse redundant lines in order to have a concise component. The order of the elements follows the order showed in the chart.
![01](https://user-images.githubusercontent.com/52999439/79008140-04261100-7b5d-11ea-84a3-0a43e49d7138.jpg)
![02](https://user-images.githubusercontent.com/52999439/79008147-0a1bf200-7b5d-11ea-9323-c6ed78bb9dbc.jpg)

**Comment by stegue88** [comment]
After discussion with the team, we moved to a “minimal” version that seems to work better, but exceptions to the format are to be considered (i.e bubble charts)

2 - We collapse redundant lines in order to have a concise component. The order of the elements follows the order showed in the chart.
![02](https://user-images.githubusercontent.com/52999439/79008304-5bc47c80-7b5d-11ea-91d2-92923125fc8c.jpg)

**Comment by stegue88** [comment]
Further explorations around the edge case of long labels:
The long name could be truncated at 2/3 lines; space is kept between the two columns to avoid overlapping; we suggest the number to be aligned with the last line of the label.

Long labels in the legend could have their own space on a new line, or could be truncated as well and have their tooltip while hovering.

Font-wise, using different fonts helps to visually distinguish between columns and gives hierarchy of information.

![03](https://user-images.githubusercontent.com/52999439/79008473-c970a880-7b5d-11ea-81ce-ac81a503aaf1.jpg)

**Comment by stegue88** [comment]
Lastly, we tried separating the metrics more explicitly (using a line in between every metric / separating grouped datapoints form standalone ones), but we feel it create disorientation, feels weird to the eye and messy. It would create unintended separation in single tooltip too.
![04](https://user-images.githubusercontent.com/52999439/79008980-d2ae4500-7b5e-11ea-9bee-4f496613fda5.png)
![05](https://user-images.githubusercontent.com/52999439/79008987-d3df7200-7b5e-11ea-8f4b-d4aa3af2afba.png)

**Comment by theiliad** [comment]
Tagging @mjabbink here as well so he can see the progress.

I'm not a big fan of the grey divider lines. I know Mike is really in favor of those.

The rest looks good to me. I think if we build a dimension-based tooltip we should be in good hands... we'll just add as many dimensions as exists within the vertical line

**Comment by sadekbazaraa** [comment]
@theiliad @mjabbink I don't mind the light gray horizontal lines in the particular example above BUT I do see where it might get quite busy and problematic when there's many elements such as the line chart or scatterplot. 

I was going to suggest simplifying the number of horizontal lines to be used only when separating elements that are more distinct. I think this is starting to happen in the bottom right two charts in the image above. In the "Tickets by category" example, maybe we just have a line separating "Category...Sold" from the Dataset items instead of having one between every item in the list?

**Comment by mjabbink** [comment]
@theiliad @stegue88 @sadekbazaraa I feel the opposite about the light grey lines. I think they provide focus and clarity when looking at the tooltip. 

These read well and look great to me.

<img width="714" alt="Screen Shot 2020-04-13 at 2 55 49 PM" src="https://user-images.githubusercontent.com/32881239/79155640-0d022700-7d97-11ea-99b3-f4ce6445f3b1.png">

——————


<img width="667" alt="Screen Shot 2020-04-13 at 2 54 52 PM" src="https://user-images.githubusercontent.com/32881239/79155648-12f80800-7d97-11ea-8dbb-3a2b2be40f86.png">

**Comment by mjabbink** [comment]
I think we should proceed with the lines and also apply to all the themes. I only see the white theme but curious to see G90/100 themself with very subtle lines

**Comment by stegue88** [comment]
white theme tooltip with light grey lines ![06](https://user-images.githubusercontent.com/52999439/80003804-d2e50380-84c1-11ea-9a55-ea01ddd8995d.jpg)

**Comment by stegue88** [comment]
G90 and G100 theme tooltip tests with lines
![07_dark](https://user-images.githubusercontent.com/52999439/80003966-0de73700-84c2-11ea-907a-74804a9455b4.jpg)

**Comment by theiliad** [comment]
looks great to me 💯

**Comment by stegue88** [comment]
Also adding this use case after yesterday talk, what the tooltip shows when axis don't have titles.
So one suggestion is to have a default label "X-axis" "Y-axis" or just show the correspondent value left-aligned.
![08 axis labels](https://user-images.githubusercontent.com/52999439/80107796-d63cc580-857b-11ea-9e1d-abccb145fe9c.jpg)

**Comment by mjabbink** [comment]
I think there is room for heading to be semibold and also I see some with the 1px background line on the left of mini color swatches which I think is needed but many don’t have this. Are we proposing that is optional?

**Comment by stegue88** [comment]
I agree, the 1px line on the left of mini color swatch helps a lot in distinguishing the tooltip from the background when there are plenty of colors (i.e. heatmap). Moreover it is very useful when we consider a dark theme, there the tooltip stands out very well.
![07_dark_1px](https://user-images.githubusercontent.com/52999439/80120365-27a08100-858b-11ea-94e2-087bc70b0189.jpg)
![02_1px](https://user-images.githubusercontent.com/52999439/80120447-4d2d8a80-858b-11ea-96cb-ade63c2db27b.jpg)

**Comment by stegue88** [comment]
As for the semibold, for sure there is physical room to have it. Although there's a consideration to be made on the meaning: are we implying that there's a hierarchy of information? Actually no... or, we don't know for sure. I'd probably leave it optional to the user to decide if and what's the most important info to highlight. (my 2cents)
![09 semibold](https://user-images.githubusercontent.com/52999439/80122918-7c91c680-858e-11ea-862d-890381c82838.jpg)

**Comment by theiliad** [comment]
🥳
