### ISSUE TITLE
Date / Time format does not support g11n

### ISSUE THREAD

**Issue by yinting-github** [carbon-design-system/carbon-charts#558]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### Issue description
The date / time format did not support multi-culture while browser language set as non-English. 

#### Steps to produce the issue
the original issue is from one of our product and developer (apatloll@in.ibm.com) told it's coming from cloudPal carbon charts we are using.

more details can be found: https://github.ibm.com/bluemix-mobile-services/bmd-project-push/issues/3594.

**Comment by theiliad** [comment]
Hi, we use `date-fns` for locales. Currently we don't support automatic switching of locales because it'll cause `@carbon/charts` to import all possible locales into your app bundle.

As mentioned above you can switch to any locale that is supported by `date-fns` (example https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/demo/data/bar.ts#L126)

And here's a list of all available locale:
https://unpkg.com/browse/date-fns@2.11.1/locale/
