### ISSUE TITLE
Pie/Donut `fillColors` option no longer working

### ISSUE THREAD

**Issue by ryanomackey** [carbon-design-system/carbon-charts#575]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:

0.30.9 (worked as expected on 0.29.8, so break happened somewhere in this range)

### Issue description

The Pie/Donut chart used to take a `fillColors` option that would allow the user to set a custom color scheme

#### Steps to produce the issue

```jsx
  // Define some custom colors
  const colors = ['#370764', '#7820D1', '#0F62FE', '#6AB0FF', '#C5DEFF'];

  const data = {
    labels: ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5' ],
    datasets: [
      {
        // Include with one of the datasets
        fillColors: colors,
        data: ['$1.00', '$2.00', '$3.00', '$4.00', '$5.00'],
      },
    ],
  };

  <Donut data={data} />
```

#### Current behavior

![image](https://user-images.githubusercontent.com/17710824/79266045-9af41580-7e5c-11ea-9e07-b1a19aed148b.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/17710824/79266098-ac3d2200-7e5c-11ea-95c4-c678f8ad5b4c.png)

**Comment by theiliad** [comment]
Hi, in version `0.30.8` we switched to a tabular data format, that's when this happened.
https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials--tabular-data-format

We added backwards compatibility to most of the pieces of the older data format, however `fillColors` was one that couldn't be fully backwards compatible because of the difference between the old and new approach.

The breaking change is a minor one and described in the link above.

Please use the new color scale option shown in the link
![image](https://user-images.githubusercontent.com/14989804/79269043-cf220300-7e69-11ea-80b6-ac0e47de27b4.png)
