### ISSUE TITLE
Proposed candlestick chart

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon-charts#597]
#### I am submitting a...

- [ x] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [x ] Other (design proposal)

### Issue description
Carbon advanced charts does not include candle stick charts so DB2 designed their own:

<img width="368" alt="candle-stick chart" src="https://user-images.githubusercontent.com/63752979/80240786-4ea49480-8617-11ea-96d6-58726ef0105e.png">

In this context we want to show what is my current cpu consumption at that particular time. The candle stick just means that at that given time what is my Min/Avg/Max consumption.

**Comment by tifftea** [comment]
@yayitsnatasha

**Comment by theiliad** [comment]
@designertyler how readable do we think this is to a user just to look at CPU consumption data?

Is there a more readable way to visualize this data?

**Comment by pjrdata** [comment]
For CPU consumption, it doesn't normally matter what the first and last values are but when using a true candlestick chart, the Open and Close values are critical. An hourly box plot is a good way of showing cpu data in a way similar to that "candlestick" chart above but the chart shown does look ok - though it's unclear what the box is actually indicating, is it average or something like that? I doubt it is the measures at start/end of the interval because they would rarely be so close, especially given the wide gap between min and max as shown.

**Comment by mgarsteck** [comment]
Is there any progress on this? Would love to switch over but need the candlestick chart

**Comment by theiliad** [comment]
> Is there any progress on this? Would love to switch over but need the candlestick chart

Hi, unfortunately this chart isn't on our roadmap. Would you like to help contribute it to our library by any chance? 🙂

**Comment by mgarsteck** [comment]
absolutely :)

**Comment by theiliad** [comment]
> absolutely :)

Fantastic!

I had this PR a few years back https://github.com/carbon-design-system/carbon-charts/pull/1119, however never got a chance to finish it out.

Also, pls lmk if you need a `get started` guide on this, and I can set it up

**Comment by mgarsteck** [comment]
Sure, anything that helps me get integrated into the ecosystem :)

**Comment by theiliad** [comment]
> Sure, anything that helps me get integrated into the ecosystem :)

@mgarsteck could you pls give me an email addr to setup a meeting with?

**Comment by theiliad** [comment]
Not much demand around this feature
