### ISSUE TITLE
Alluvial diagram - Explorations

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/carbon-charts#871]
Working [Box Note](https://ibm.box.com/s/yba0ie4522utyyfain342fxukn4lzbn1)

**Comment by theiliad** [comment]
🎉

**Comment by sarahpedregon** [comment]
### Description: 
Define alluvial diagrams so that we can give guidance for them in the Data Visualization [Advanced Charts](https://www.carbondesignsystem.com/data-visualization/advanced-charts/) section in IBM's [Carbon Design System](https://www.carbondesignsystem.com/). 

**Resources**
1. [Alluvial Diagram Audit Mural](https://app.mural.co/invitation/mural/carboncharts6255/1606856128837?sender=cecalder&key=68fa83d7-fe13-4ffb-9394-67db997b8c74)
2. [Alluvial Diagram Roadmap](https://app.mural.co/invitation/mural/carboncharts6255/1610659597756?sender=sarahpedregon8145&key=bab0486b-d57d-48b5-abbb-a49d95cce3e8)
3. [Box Folder](https://ibm.box.com/s/bm3g3d4b1sokoqh0d2by0bb76cr2j37z)

**To reference:** 

[Network Diagram Moodboard](https://app.mural.co/invitation/mural/carboncharts6255/1602613883345?sender=cecalder&key=30859176-13a1-477a-b7b9-a2c7c5386801)


**Work to be done**

- [ ] Roadmap
- _What are our milestones_
- [ ] Audit
- _Define what an alluvial diagram is__
- _What are the commonalities? What elements provide the most clarity for reading an alluvial?_
- _**Things to audit:** use of color, accessibility, customization, opacity, clarity, pagination, behaviors, etc._
- [ ] Design Explorations (defining what is entailed is TBD)
- [ ] Provide Assets to Carbon (defining those assets is TBD)
