### ISSUE TITLE
Question about theming

### ISSUE THREAD

**Issue by ispyinternet** [carbon-design-system/carbon-charts#892]
Is it possible to build the scss in such a way that you can allow theme selection after build, i.e build the different theme tokens into css vars and reference these in the styles (like the carbon-component demo's)?

**Comment by theiliad** [comment]
Hi, since SCSS styles always need to compile to CSS, you can't pull them in in real-time. You would add each themed set of styles to an element, binding them to different classnames. See the example below:

https://github.com/carbon-design-system/carbon-charts/blob/b41033a010a46fad1246e59ee26cd3d5004abb98/packages/core/demo/styles.scss#L31-L111

**Another** option that you have is swapping CSS imports in your page based on the theme that needs to be applied (read the `If using CSS` section of this doc https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials--themes)

**Comment by ispyinternet** [comment]
Cheers, the demo code is exactly what I was looking for.
