### ISSUE TITLE
Line Charts time series with 22k points: How to speed up and make readable?

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon-charts#926]
#### I am submitting a...

- [x ] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
"@carbon/charts-react": "^0.41.14",
#### Current behavior
Line Charts time series with 22k points: How to speed up and make readable?

**Comment by theiliad** [comment]
> #### I am submitting a...
> * [x ] Feature request
> * [ ]  Design defect
> * [ ]  Source code defect
> * [ ]  Demo/documentation defect
> * [ ]  Other
> 
> #### charts version:
> "@carbon/charts-react": "^0.41.14",
> 
> ### Issue description
> #### Steps to produce the issue
> #### Current behavior
> Line Charts time series with 22k points: How to speed up and make readable?
> 
> #### Expected behavior
> ### Screenshot or recording

Hi,
22 thousand points are definitely a lot! Carbon Charts use SVG rendering for accessibility reasons.

There are other libraries that use hardware-accelerated technologies which can render a lot more datapoints however aren't accessible to screen readers because they're not rendering in SVG.

I would start by using the zoombar and an initially zoomed in chart where you don't see all 22k datapoints, however you're still probably pushing the limits too much. Is there anyway that you can reduce your number of datapoints?

I wouldn't be surprised if even the other hardware-accelerated libraries aren't able to properly render that amount of datapoints

**Comment by theiliad** [comment]
https://carbon-design-system.github.io/carbon-charts/?path=/story/zoom-bar-alpha--line-time-series-time-interval-15seconds-zoom-bar-enabled-initial-zoomed-domain

**Comment by biapar** [comment]
Hi,
I’ve not tried other libs because I wouldn’t mix chart libs. 
Now, I worked sql server side to aggregate data by 10 minutes instead seconds. So I reduce the points of each five series and the graph works. 
Which react chart lib do you suggest for this amount of data?

**Comment by theiliad** [comment]
I would be seriously surprised if any of the libraries can handle more than 5k points unless they're using WebGL. Even still it's not just about rendering, any processing over the data by the library will take long...

If you're using charts in an IBM product, please use Carbon Charts so that you product complies with the design language. I would talk over with a data scientist and/or UX designers/researchers in your team to figure out whether/how they can reduce the amount of data

**Comment by biapar** [comment]
I reduce the data to 5k points doing the average data of 10 minutes slots instead each 15 seconds.

**Comment by MichaelTendoSsemwanga** [comment]
I'm facing similar issue

My charts is around 1000 points but its too slow and not usable
Any advice on how to optimize?
This is my options:


  const options = {
    title: "Combo",
    legend: {
      enabled: false,
    },
    tooltip: {
      // enabled: false,
    },
    points: {
      radius: 0,
    },
    axes: {
      left: {
        stacked: true,
        scaleType: "linear",
        mapsTo: "value",
        correspondingDatasets: posGroups,
        includeZero: true,
        domain: [negativeSumMin, positiveSumMax],
      },
      right: {
        stacked: true,
        scaleType: "linear",
        mapsTo: "value",
        correspondingDatasets: negGroups,
        includeZero: true,
        domain: [negativeSumMin, positiveSumMax],
      },

      bottom: {
        scaleType: "time",
        mapsTo: "date",
      },
    },
    comboChartTypes: [
      {
        type: "stacked-area",
        correspondingDatasets: posGroups,

      },
        {
         type: "stacked-area",

         correspondingDatasets: negGroups,
        },
    ],
    height: "400px",
    theme: "g100",
  };
