### ISSUE TITLE
Area chart with set domain renders data points as straight line unless resized

### ISSUE THREAD

**Issue by kleyu** [carbon-design-system/carbon-charts#937]
#### I am submitting a... 

- [ ] Feature request
- [ ] Design defect
- [x] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

#### charts version:
```json
"@carbon/charts": "^0.41.27",
"@carbon/charts-react": "^0.41.27",
```

### Issue description

When setting a custom domain on Area chart, it renders a straight line instead of expected area.

#### Steps to produce the issue

1. Open codesandbox
https://codesandbox.io/s/async-wind-5fbow

2. See that charts is not rendered correctly
3. Resize the viewport
4. It works as expected
#### Current behavior

Renders a straight line

#### Expected behavior

Renders an area

### Screenshot or recording

I think codesandbox example is enought. Let me know if you need help reproducing the issue.

**Comment by theiliad** [comment]
Hi, please **always** use JS-dates instead of date strings

![image](https://user-images.githubusercontent.com/14989804/106014916-f3af3a80-608b-11eb-9e48-9e36911a72eb.png)

In the event that you provide string dates, we try our best to sanitize the values provided however JS-dates are the standard.

By updating to the values above I was able to get your demo working
